### ISSUE TITLE
Total audio shows "MB" suffix

### ISSUE THREAD

**Issue by masenf** [slavik0329/ham2mon-gui#10]
![image](https://user-images.githubusercontent.com/1524005/92971969-44ecc380-f436-11ea-8cd5-3ef96e1302d3.png)

Minor display issue that would probably be simple to fix.

**Comment by slavik0329** [comment]
@masenf It will be.

Thanks for submitting this and the other issues. I will try to complete most. I'm happy to see others actually using this app. I spent weeks trying to make it perfect, but had no initial users.

**Comment by slavik0329** [comment]
This has been fixed and merged into master

**Comment by masenf** [comment]
Looks good 
![image](https://user-images.githubusercontent.com/1524005/92974243-9f881e80-f43a-11ea-81b7-2b69323a29d7.png)

The only problem I see is that the calculation is assuming 16kbps per second. I'll go comment on issue #7
