### ISSUE TITLE
added bits for a Debian (Bullseye, maybe all) build

### ISSUE THREAD

**Issue by k9wkj** [slavik0329/ham2mon-gui#2]
deps include
Cmake
Build Essential  
Yarnpkg  

in the build/install instructions
all "yarn" to be "yarnpkg"

very nice work so far
makes Ham2mon even more useful

**Comment by slavik0329** [comment]
The only mail dependancy for this GUI is Node.js

You may need Build Essential and Cmake before npm or Yarn is able to compile the other dependencies, but usually installing Node.js covers those other deps.
